#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 23, 2020 01:34:58 PM EST  platform: Windows NT
#    Nov 24, 2020 02:33:33 PM EST  platform: Windows NT

import sys
import gamer1_support

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global profilename
    profilename = tk.StringVar()
    global usertype
    usertype = tk.StringVar()
    global spendingrange
    spendingrange = tk.StringVar()
    global platformtype
    platformtype = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

import query

def open_query():
    print('profile_support.open_query')
    sys.stdout.flush()
#    currentuser = username.get()
    for i in gamer1_support.users:
        if i.get("username") == gamer1_support.currentuser:
            currentRec = i
            break
    print(gamer1_support.currentuser)

    currentusertype = usertype.get()
    currentspendingrange = spendingrange.get() #i.get("spendingrange")
    currentplatformtype = platformtype.get()  #i.get("platformtype")

    addrec = { "username": profilename, "usertype" : usertype, "spendingrange": spendingrange, "platformtype" : platformtype }

    gamer1_support.currentuser = profilename
    gamer1_support.currentspendingrange = currentspendingrange
    gamer1_support.currentplatformtype = currentplatformtype

    gamer1_support.users.append(addrec)

    query.create_query(root)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import profile
    profile.vp_start_gui()





