#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 23, 2020 02:12:29 PM EST  platform: Windows NT
#    Nov 25, 2020 10:24:02 AM EST  platform: Windows NT
#    Nov 27, 2020 10:59:36 AM EST  platform: Windows NT

import sys
import gamer1_support

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global gamelist
    gamelist = tk.StringVar()
    global daterange
    daterange = tk.StringVar()
    global costrange
    costrange = tk.StringVar()
    global gameplatform
    gameplatform = tk.StringVar()
    global gametype
    gametype = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    daterange.set("*")
    spend = gamer1_support.currentspendingrange
    costrange.set(spend)
    #print(costrange);
    platform = gamer1_support.currentplatformtype
    gameplatform.set(platform)
    print('query_support init ')
    print(platform+spend)
    gametype.set("*")


game1list = "game1\ngame2\ngame3\ngame1\ngame2\ngame3\ngame1\ngame2\ngame3\ngame1\ngame2\ngame3\n"
def start_query():
    print('query_support.start_query')
    gamelist.set(game1list)
    sys.stdout.flush()

def stop_query():
    print('query_support.stop_query')
    sys.stdout.flush()

def hide_window():
    # Function which closes the window.
    global top_level
    top_level.withdraw()

import gamer1_support

def exitall():
    print('query_support.exitall')
    sys.stdout.flush()
    gamer1_support.destroy_window()

def destroy_window():
    # Function which closes the window.
    global top_level
    gamer1_support.destroy_window()
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import query
    query.vp_start_gui()





